### ISSUE TITLE
errors when reindexing a bunch of datasets

### ISSUE THREAD

**Issue by albanm** [koumoul-dev/data-fair#51]
Mostly this:

Failure in worker finalizer Error: [line][VPKoA2MBgQd4eqRL1Dj2]: version conflict, current version [2] is different than the one provided [1]
    at esClient.update.err (/webapp/server/utils/extensions.js:236:25)
    at respond (/webapp/node_modules/elasticsearch/src/lib/transport.js:326:9)
    at checkRespForFailure (/webapp/node_modules/elasticsearch/src/lib/transport.js:266:7)
    at HttpConnector.<anonymous> (/webapp/node_modules/elasticsearch/src/lib/connectors/http.js:159:7)
    at IncomingMessage.bound (/webapp/node_modules/lodash/dist/lodash.js:729:21)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

But also:

Failure in worker finalizer Error: no such index
    at esClient.update.err (/webapp/server/utils/extensions.js:236:25)
    at respond (/webapp/node_modules/elasticsearch/src/lib/transport.js:326:9)
    at checkRespForFailure (/webapp/node_modules/elasticsearch/src/lib/transport.js:266:7)
    at HttpConnector.<anonymous> (/webapp/node_modules/elasticsearch/src/lib/connectors/http.js:159:7)
    at IncomingMessage.bound (/webapp/node_modules/lodash/dist/lodash.js:729:21)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

Also add a functionality to diagnose datasets in error. Maybe an admin or at least a script.

**Comment by albanm** [comment]
I think finalization subjects ES to a lot of stress.. We should try to optimize it or slow it down voluntarily.

Bulk updates ?

Maybe we should reduce workers concurrency ?

**Comment by albanm** [comment]
Failure in worker indexer { Error: [search_phase_execution_exception] all shards failed
    at respond (/webapp/node_modules/elasticsearch/src/lib/transport.js:307:15)
    at checkRespForFailure (/webapp/node_modules/elasticsearch/src/lib/transport.js:266:7)
    at HttpConnector.<anonymous> (/webapp/node_modules/elasticsearch/src/lib/connectors/http.js:159:7)
    at IncomingMessage.bound (/webapp/node_modules/lodash/dist/lodash.js:729:21)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  status: 503,
  displayName: 'ServiceUnavailable',
  message: '[search_phase_execution_exception] all shards failed',
  path: '/dataset-production-koumoulmajic/_search',
  query: {},
  body: 
   { error: 
      { root_cause: [],
        type: 'search_phase_execution_exception',
        reason: 'all shards failed',
        phase: 'query',
        grouped: true,
        failed_shards: [] },
     status: 503 },
  statusCode: 503,
  response: '{"error":{"root_cause":[],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[]},"status":503}',
  toString: [Function],
  toJSON: [Function] }

**Comment by albanm** [comment]
Failure in worker finalizer TypeError: Cannot read property '0' of undefined
    at isPointOnLineSegment (/webapp/node_modules/@turf/clean-coords/index.js:143:23)
    at cleanLine (/webapp/node_modules/@turf/clean-coords/index.js:116:9)
    at cleanCoords (/webapp/node_modules/@turf/clean-coords/index.js:35:25)
    at Object.exports.geometry2fields (/webapp/server/utils/geo.js:46:3)
    at CalculatedExtension._transform (/webapp/server/utils/extensions.js:341:37)
    at CalculatedExtension.Transform._read (_stream_transform.js:186:10)
    at CalculatedExtension.Readable.read (_stream_readable.js:442:10)
    at flow (_stream_readable.js:846:34)
    at ESOutputStream.<anonymous> (_stream_readable.js:707:7)
    at emitNone (events.js:106:13)
    at ESOutputStream.emit (events.js:208:7)
    at onwriteDrain (_stream_writable.js:464:12)
    at afterWrite (_stream_writable.js:452:5)
    at onwrite (_stream_writable.js:445:7)
    at esClient.update.err (/webapp/server/utils/extensions.js:238:7)
    at respond (/webapp/node_modules/elasticsearch/src/lib/transport.js:328:9)
    at checkRespForFailure (/webapp/node_modules/elasticsearch/src/lib/transport.js:266:7)
    at HttpConnector.<anonymous> (/webapp/node_modules/elasticsearch/src/lib/connectors/http.js:159:7)
    at IncomingMessage.bound (/webapp/node_modules/lodash/dist/lodash.js:729:21)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)

**Comment by albanm** [comment]
The whole process as been made more robust. i think this is no longer relevant.
